### ISSUE TITLE
Aiming for PEPM 2020?

### ISSUE THREAD

**Issue by alhassy** [alhassy/next-700-module-systems#24]
Please see commit a7b9ac9 or, temporarily, [here](https://alhassy.github.io/next-700-module-systems/papers/Paper1.pdf) for the PDF of rough notes for ideas to be submitted to PEPM 2020.

In-particular:

0. Do the ideas in the rough notes communicate something somewhat useful to submit as a paper?

1. If so, please provide direction on the particular question marks interspersed in the document.

**Comment by JacquesCarette** [comment]
The title talks about semantics, but the abstract doesn't, it's about generativity of variants.
Section 2 is titled 'grammar', but quickly gets into fold. Fold is perhaps some kind of operational semantics for some operators, but is not "semantics" more broadly than that. Writing down a proper grammar for a language is trickier than it sounds. You need to actually write one [in Agda, of course].
The ideas of M-Set and so on could be nice - if they can be made fully precise, and contrasted with the same ideas from universal algebra.
There are many ideas in here (many of which could be the basis for a paper) - but they are only very loosely connected. And un-realized. What is the main take-home message?

Maybe PEPM is too soon.  I think there are 2 ideas you should be working on:
1. pick a small DTL (hopefully reusing an existing one), and show that it is expressive enough to express parametrized theories in equational logic (i.e. so that both Monoid and Monoid Homorphism can be expressed internally). Implement it in Agda. Show that the representation you have is adequate. Implement a denotational semantics from the language to MLTT, i.e. to Agda. Show that you have a transformer from the representation of Monoid to Monoid Homomorphism. [Of course, for exactly equational logic, this has already been done, so you'll need to go a little bit beyond]. But many more transformers should be in scope too.  Including bundling/unbundling!!! [which is not within reach of equational logic because it's too first-order for that]. Lots of meta-theorems to prove on the way.

2. Implement PackageFormers in Haskell, for Agda.

Both of those are in a straight line between now and your Ph.D.  Working on those will get you there fastest.

**Comment by JacquesCarette** [comment]
This is obviously obsolete - closing.
