### ISSUE TITLE
ICFP 2020 :: 3-for-1 Monadic Notation: Do-it-yourself module types

### ISSUE THREAD

**Issue by alhassy** [alhassy/next-700-module-systems#26]
Any feedback regarding the tremendously rough draft would be super helpful!

Besides [the draft](https://github.com/alhassy/next-700-module-systems/blob/master/papers/Paper2.pdf), there is also [its associated code](https://github.com/alhassy/next-700-module-systems/blob/master/papers/paper2.agda), as well as the associated [library code](https://github.com/alhassy/next-700-module-systems/blob/master/papers/Paper2.pdf) which may be [read literately here](https://github.com/alhassy/next-700-module-systems/blob/master/prototype).

The [ICFP deadline](https://icfp20.sigplan.org/track/icfp-2020-papers#Call-for-Papers) is March 3 ---next week--- with a 25 page limit using acm-small; the draft is at 13 single-column pages.

**Comment by JacquesCarette** [comment]
[This is a copy of my email feedback]

Small point:  What do you mean by "typeclass"?  I think that's a misleading, Haskell-ism that is not generally helpful for many users.

I will definitely look at both as soon as possible, but I'm still catching up. Note that the preprint contains a lot of unnecessary qualifiers in the text write-up (from a quick glance at the first page).  You over-use "folklore" and "traditionally", and can just delete words like "humblest", "uninsightful" (and likely avoid "natural", etc).

The paper should probably be structured as follows
1. Introduction
  - Gives a careful description of "what problem needs to be solved"
  - Does it by giving specific example of 'the problem'
  - Does not give any solution pieces whatsoever, but may point in the right direction
  - May give "pseudo code" solutions, that gives the right flavour but abstracts away from concrete noise
2. Background
  - Gives a quick introduction to the assumed information the reader needs to understand the deeper problem and its solution
  - Techniques (for example, monads and do notation in Agda, reflection, etc)
3. Definitions
  - Defines terms of the problem formally
  - Illustrates the definitions via explicit examples
4. Solution
  - Give the general solution to the problem
5. Semantics
  - What does it all mean?

and we can then see what's missing.

Your current write-up would not make sense to anyone other than us 3 [and even then...].  You have to explain what you're doing to others; you may make the (explicit!) assumption that your readers will know Agda and thence, dependent type theory. You may not assume that they are aware of the existence of the problems you're solving.

Your current table 1 is key to the motivation: there you present 5 pieces of information that are, somehow, "the same".  If not "the same", then at least are highly compressible, i.e. there is some 'core' information that they all share, and then it gets rephrased in different ways.

Can you also put the text in the right format?  Proper display of information depends crucially on that.

**Comment by WolframKahl** [comment]
My original thought for an ICFP paper was a pearl that would only concentrate on the Agda side,
without evening mentioning the E-Lisp side, because I thought that that would be easier to turn into a coherent and convincing story. Also, to my eyes, the presence of E-Lisp would considerably rob any pearl of its luster.

For ICFP, I also see no reason to attempt/pretend to be language agnostic when all you show is Agda.
(The re-usablility of the approach to other languages/settings could be mentioned in the conclusion.) 

In your current thoughts, does  “the PackageFormer editor extension” (citation and appropriate introduction missing!!!)  enter only the “Semantics for PackageFormer” section. as an application?

I have parsing problems with both occurrences of two `\spot`  in the first paragraph of section 1: One  Σ too many, one λ too few?

(Do I need to read the current version, or will we get an update implementing (some of) Jacques' suggestions soon?)

**Comment by jbarthelmes** [comment]
https://github.com/alhassy/next-700-module-systems/blame/master/papers/Paper2.org#L664 the variable should be `S`, not `X`; right?

**Comment by alhassy** [comment]
@jbarthelmes Yes! Thanks; I've also restructured the paper ---it ought to be less erratic/strenuous to read now ^_^

**Comment by JacquesCarette** [comment]
Paper since rejected.
