### ISSUE TITLE
PhD Thesis Writing

### ISSUE THREAD

**Issue by alhassy** [alhassy/next-700-module-systems#27]
Hello!

I've written a brief [Story](https://github.com/alhassy/next-700-module-systems/blob/master/thesis.lagda.org#story) that is intended to be the guide for writing the thesis.

It, more or less, tells the story of how we got to where we are right now.

From that, I've extracted a more detailed [outline](https://github.com/alhassy/next-700-module-systems/blob/master/thesis.lagda.org#outline).

Any feedback on these items before I began to write large chunks of sections would be appreciated ^_^

**Comment by JacquesCarette** [comment]
Good.  We can definitely start from those (both story and outline), as far as I am concerned.

Moving on, here are two things to seriously think about:
1. Motivating examples. There should hopefully come from external sources (if at all possible). The main thing is that the examples should recur in the story of the thesis, to help concretize each of the points being made. New examples can be used to deepen things too, but some basic ones should be used from start to end
2. related work: my feeling is that, for the thesis, it would be better if it was done after Background rather than at the end. It will give the reader a better grounding of where 'your' work starts.

**Comment by alhassy** [comment]
I've written some cool looking code in Coq to demonstrate its module system, then translated that into Agda in a disciplined fashion: No use of Agda's `module` keyword. I think this translation is cute ^_^

https://github.com/alhassy/next-700-module-systems/blob/master/thesis.org#modules-in-coq-then-in-agda

**Comment by WolframKahl** [comment]
> No use of Agda's `module` keyword.

You are cheating, since you use `record` declarations without `field`s, that is, only the module side of `record`s.

Are you on agda-2.6.1?

> I only did the case analysis, the rest was “auto”. 

(Just curious: Can this be turned into a tactic invocation in Agda?)

**Comment by alhassy** [comment]
Exactly! Agda's `record` suffice in-place of its `modules`.

- Yes, I'm on 2.6.1.
- Yes, with a bit of Elisp, it can become an editor tactic ;-)

**Comment by JacquesCarette** [comment]
It feels like this issue is long stale and should be closed?

**Comment by alhassy** [comment]
Perhaps it should be closed when writing is actually complete.

Or do you mean to close it since discussions primarily occur via email, rather than taking place here on github.

**Comment by JacquesCarette** [comment]
The story link is dead (and the story probably has changed). Same for outline. The issue, as a "good" issue, was about just those 2 things. "Thesis writing" is a project, not a single-issue.

Issues should be "small morsels" that can be dealt with in a timely manner, not something huge and long-lived.

**Comment by alhassy** [comment]
That sounds reasonable! ^_^
