### ISSUE TITLE
4.1 editor extension

### ISSUE THREAD

**Issue by JacquesCarette** [alhassy/next-700-module-systems#29]
This is based on commit 2a1878f

- "... provides an extension mechanism ... neither is particular appealing". [Minor: particular -> particularly].  "particularly appealing" is too much of a subjective judgement. You can say "but both have drawbacks" (which you then indeed enumerate).
- "The former is dangerous ..." what you describe here is *hacking in* a new feature. That is indeed dangerous. What about designing a new feature instead? Do some theory, figure out what it out to be, implement it. No problem. [see below]
- "latter is tiresome" this is specious. You could create a Makefile by which you do all your compilations that automates this. You could put in a hook in the IDE (emacs) to do this.  Your editor extension is exactly a pre-processor. It's just a well-integrated one.
- "a middle-road is not always possible". While this is true, this is also not applicable, as your editor extension is not a 'middle road'. It's a convenient preprocessor. [I had written "It's just a", but realized that that kind of phrasing is exactly the kind of stuff that I'm trying to get you to stop doing.]

This is somewhat all moot anyways. Your real story is that you needed to write a **prototype** to really understand what was going on. Because it was a 'figuring out' exercise, hacking the compiler is indeed not a good idea. Implementing it as an external preprocessor is feasible, but it turns out that there's another way that has a nicer usability profile: an IDE extension.

Your bolding of **reasonable** here is unreasonable. 

Figure 4.1 does not help at all. I don't want to explain the many ways in which it is misleading. You should remove it.

**Comment by alhassy** [comment]
1. Acceptable change.
2. No change. The "do some theory" is precisely the purpose of the prototype; as you said, for figuring things out. As mentioned in the sentence you're referring to: "altering the grammar of a language requires non-trivial propagated changes throughout its codebase, but even worse, it could lead to existing language features to suddenly break due to incompatibility with the added features. " I believe that sentence suffices as a terse rebuttle to "Do some theory, figure out what it out to be, implement it. No problem."
3. No change. Having to invoke a makefile may not be as easy as "C-c C-l" in Emacs or pressing the "play button" In Visual Studio.  The point of that sentence is a setup for the next one: The need for a "well-integrated" preprocessor.
4. No change. "Convenient" is only a subpart of what I intended to communicate by "middle-road": The key point being, we avoid the extremes discussed in the sentences leading up.
5. Acceptable change. I'll include this important observation.
6. No change. I'm trying to suggest that the middle-path I've been outlining is reasonable, and so the bold font is in alignment with those goals. I'm open to change if you explain your viewpoint.
7. No change. Again, the purpose of the figure is to provide a quick overview of why an editor extension is appealing: It is a reasonable middle-road that avoids the extremes discussed thus far.  I'm open to change if you explain your viewpoint.

Once we're in agreement, the changes will be made.

**Comment by JacquesCarette** [comment]
Can you please revisit this? I think you're misinterpreting my comments - and definitely main point, that you need to tell this part of the story in a compelling way, and that this part of 4.1 does not succeed for me. It does for you, but you're too close to the topic.  What about someone who is really far from the topic?

Remember, I think your choices here were very good. There are compelling reasons to do exactly as you did. My problem is that you're not writing those reasons in a way that I find convincing. It seems that you put the emphasis on the 'wrong' parts. For example: the usability of a prototype is really not very importance. Its use as a testing ground for the ideas, and its ease of development, are quite important. That it might be usable too would be a nice bonus.

**Comment by alhassy** [comment]
This seems obsolete - closing.

**Comment by JacquesCarette** [comment]
Again, at a shallow level, this is indeed 'obsolete'. But, as I review your new chapter 4, will I find that the ideas, rather than the exact words, are still not right? Will I have to end up writing an issue like this one again?  Or can you convince me that you've actually understood the spirit of each of the points, and actively dealt with them? That would make me much happier to think that this should indeed get closed.

**Comment by alhassy** [comment]
As of the most recent commit, 4.1 has been rebranded as 6.1 and totals roughly a page and a half.

Concerns not addressed directly in the text itself are addressed in the margin.
