### ISSUE TITLE
Introduction to ch. 5

### ISSUE THREAD

**Issue by JacquesCarette** [alhassy/next-700-module-systems#41]
(read from `thesis.pdf`).  The style here harkens back to somewhat earlier writing, and needs to be revised (which I understand will be done for the margin-ful version).  But things to remember when editing:
1. `Context` is probably **not** a 'module system'. [It is still extremely useful!]
2. in point 1 you claim to show that "Languages with sufficiently powerful type systems and meta-programming can conflate record and term datatype declarations into one practical interface"; this is an over-statement on at least two fronts: 1) this is mostly shown via example, and 2) only for Agda. I do believe that you *can* show this - but if you want to claim it, you need to actually show it.
3. 'on-demand' is not good CS terminology. I believe you might mean 'dynamically'? You should be clearer.
4. point 3 "... as simple as..." would require an actual evaluation. That would take too much time. Choose less loaded words instead. [There is a strong current in CS right now to not let informal claims like this going unjustified.]
5. "Astonishingly": to whom? This is obvious to people who know enough category theory. You should not be astonished either. Instead, you should show these examples (as you do), and then explain the reason for them, in careful and precise categorical terms.
6. "The informal form is presented with the understanding that such functions need to be extended homomorphically..."  Showing this formally is not hard. I've (re)written the code to do this (in Haskell, using Lenses, for the Tog-based prototype), and it's a few easily explained lines of code. This is core to your Ph.D. thesis, you **must** explain this in careful, precise, mathematical detail.

**Comment by alhassy** [comment]
1. Will change `module system` to `packaging mechanism`.
2. Both your claims are false: It is not "via example" since we actually produce a **mechanized algorithm** and it is "not only for Agda" since we show the main syntactic manipulations in dashed boxes.
3. Will use `dynamically, on demand`. Your feedback could be clearer; e.g., why is not good terminology.
4. The two concepts in that phrase are the same thing, hence "as simple as" could just as well have been replaced by "=".
5. "Obvious" sure, but who has **actually done this** in a modern programming language? @WolframKahl  do you know of anyone who has done this? The mechanization is the astonishing aspect: There is a lot of folklore that is either not formal or not formalised ---recall how the obvious nature of free bags is not so obvious when **actually** formalised.
6. The second part is not necessary since the full Agda listing is provided.

Please keep in mind that the goal is a "pass", not "great" nor "superb".

**Comment by JacquesCarette** [comment]
1. Excellent
2. Being wrong is best here, since it gets you closer to being done.  So I'm digging into the documentation, like that of `!-type`. Is `Term` defined anywhere?  Also, this seems like a partial function - is that documented?   The 'source' should not be "for the interested reader" here, as it is an extremely important part of your contribution.
3. fine
4. if the goal is to "pass", why are you fighting to keep in subjective phrases that could get you in trouble?
5. I agree, in a sense, as I was working on a Pearl paper to show just that.  The point is that 5.4 is a hand-written collection of a few examples. It is not systematic nor meta-programmed. 5.4 does not go beyond an interesting observation, even though there really is more here. That's the issue: the people most likely to understand what you've done will not be astonished. But they would be quite pleased to see a well-explained, systematic implementation.
6. Agda code cannot replace an explanation. And, unfortunately, I'm not getting a feeling that I have seen "the full Agda listing". Why don't I get that feeling?

I don't know why @WolframKahl does not show up as a participant, even though he's clearly tagged. Odd.

**Comment by alhassy** [comment]
1. good
2. `Term` is nullary ADT, as shown in the section `Reflection` ---now moved to new chapter 5.1; "tutorial style".
      Removed the suffix of the `Source` tags; new chapter 5.5 to address language agnostic claims.
3. ok
4. Full item deleted ---the time for discussion has passed.
5. Qualifier deleted ---though I completely disagree.
6. The full listing has been shown in an appendix.

Thanks!

----

Closing since issues have been addressed in the most recent commit.
